//
//  Copyright (c) Microsoft Corporation.
//  Licensed under the MIT license.
//
//  This file has been stripped to include only icons used by myturn2.
//  To add icons, update USED_ICONS in strip-fluent-icons.py and re-run.
//

import Foundation

/// Fluent Icons (stripped subset)
@objc public enum FluentIcon: Int, Equatable, CaseIterable {
  case accessibility24Regular = 9
  case add24Filled = 47
  case add24Regular = 48
  case alert24Filled = 192
  case alert24Regular = 193
  case alertBadge24Filled = 211
  case appsList24Regular = 515
  case arrowLeft24Regular = 1099
  case arrowRepeatAll24Regular = 1224
  case arrowRight24Regular = 1282
  case arrowUpRight24Regular = 1636
  case bookmark24Filled = 2285
  case bookmark24Regular = 2286
  case briefcase24Filled = 2625
  case briefcase24Regular = 2626
  case building24Filled = 2726
  case building24Regular = 2727
  case calendar24Regular = 2950
  case calendarClock24Regular = 3084
  case calendarEmpty24Regular = 3138
  case camera24Filled = 3538
  case chat24Regular = 3826
  case checkmark24Filled = 4092
  case checkmarkCircle24Filled = 4110
  case checkmarkCircle24Regular = 4111
  case checkmarkStarburst24Filled = 4163
  case chevronDown20Filled = 4259
  case chevronDown24Regular = 4262
  case chevronLeft24Regular = 4282
  case chevronRight24Regular = 4296
  case chevronUp20Filled = 4307
  case circleHalfFill24Regular = 4350
  case clipboardTask24Regular = 4664
  case clock24Regular = 4699
  case comment24Regular = 5227
  case dataBarVertical24Regular = 5864
  case delete24Regular = 6106
  case desktop24Regular = 6187
  case dismiss24Regular = 6465
  case dismissCircle24Filled = 6482
  case dismissCircle24Regular = 6483
  case document24Regular = 6571
  case edit24Filled = 7584
  case edit24Regular = 7585
  case emoji24Filled = 7660
  case errorCircle24Filled = 7814
  case eye24Filled = 7857
  case eye24Regular = 7858
  case eyeOff24Regular = 7887
  case folder24Regular = 8237
  case globe24Regular = 8795
  case grid24Regular = 8915
  case hatGraduation24Filled = 9103
  case heart24Filled = 9217
  case home24Regular = 9358
  case homePerson24Regular = 9421
  case image24Regular = 9466
  case info24Filled = 9664
  case info24Regular = 9665
  case infoShield20Filled = 9672
  case lightbulb24Filled = 10228
  case list24Regular = 10454
  case location24Filled = 10503
  case location24Regular = 10504
  case lockClosed24Filled = 10617
  case lockShield24Regular = 10674
  case mail24Filled = 10709
  case mail24Regular = 10710
  case mailInbox24Regular = 10864
  case moreHorizontal24Regular = 11428
  case people24Filled = 12474
  case people24Regular = 12475
  case peopleCommunity24Filled = 12560
  case peopleCommunity24Regular = 12561
  case person24Filled = 12782
  case person24Regular = 12783
  case personKey24Regular = 13042
  case personStarburst20Regular = 13215
  case phone24Filled = 13330
  case phone24Regular = 13331
  case phoneDismiss24Regular = 13383
  case questionCircle24Filled = 14071
  case questionCircle24Regular = 14072
  case road24Regular = 14474
  case search24Regular = 14767
  case shareIos24Regular = 15064
  case shieldCheckmark24Regular = 15188
  case signOut24Regular = 15410
  case slideTextSparkle24Regular = 15660
  case sparkle24Regular = 15781
  case speaker224Filled = 15854
  case star24Filled = 16179
  case subtract24Regular = 16419
  case tablet24Regular = 17117
  case ticketDiagonal24Regular = 18378
  case video24Filled = 18865
  case wallet24Regular = 19211
  case warning24Filled = 19253
  case warning24Regular = 19254
  case weatherMoon24Filled = 19342
  case weatherMoon24Regular = 19343
  case weatherSunny24Filled = 19439
  case weatherSunny24Regular = 19440
  case wifiWarning24Regular = 19528

  public var resourceString: String {
    switch self {
    case .accessibility24Regular: return "ic_fluent_accessibility_24_regular"
    case .add24Filled: return "ic_fluent_add_24_filled"
    case .add24Regular: return "ic_fluent_add_24_regular"
    case .alert24Filled: return "ic_fluent_alert_24_filled"
    case .alert24Regular: return "ic_fluent_alert_24_regular"
    case .alertBadge24Filled: return "ic_fluent_alert_badge_24_filled"
    case .appsList24Regular: return "ic_fluent_apps_list_24_regular"
    case .arrowLeft24Regular: return "ic_fluent_arrow_left_24_regular"
    case .arrowRepeatAll24Regular: return "ic_fluent_arrow_repeat_all_24_regular"
    case .arrowRight24Regular: return "ic_fluent_arrow_right_24_regular"
    case .arrowUpRight24Regular: return "ic_fluent_arrow_up_right_24_regular"
    case .bookmark24Filled: return "ic_fluent_bookmark_24_filled"
    case .bookmark24Regular: return "ic_fluent_bookmark_24_regular"
    case .briefcase24Filled: return "ic_fluent_briefcase_24_filled"
    case .briefcase24Regular: return "ic_fluent_briefcase_24_regular"
    case .building24Filled: return "ic_fluent_building_24_filled"
    case .building24Regular: return "ic_fluent_building_24_regular"
    case .calendar24Regular: return "ic_fluent_calendar_24_regular"
    case .calendarClock24Regular: return "ic_fluent_calendar_clock_24_regular"
    case .calendarEmpty24Regular: return "ic_fluent_calendar_empty_24_regular"
    case .camera24Filled: return "ic_fluent_camera_24_filled"
    case .chat24Regular: return "ic_fluent_chat_24_regular"
    case .checkmark24Filled: return "ic_fluent_checkmark_24_filled"
    case .checkmarkCircle24Filled: return "ic_fluent_checkmark_circle_24_filled"
    case .checkmarkCircle24Regular: return "ic_fluent_checkmark_circle_24_regular"
    case .checkmarkStarburst24Filled: return "ic_fluent_checkmark_starburst_24_filled"
    case .chevronDown20Filled: return "ic_fluent_chevron_down_20_filled"
    case .chevronDown24Regular: return "ic_fluent_chevron_down_24_regular"
    case .chevronLeft24Regular: return "ic_fluent_chevron_left_24_regular"
    case .chevronRight24Regular: return "ic_fluent_chevron_right_24_regular"
    case .chevronUp20Filled: return "ic_fluent_chevron_up_20_filled"
    case .circleHalfFill24Regular: return "ic_fluent_circle_half_fill_24_regular"
    case .clipboardTask24Regular: return "ic_fluent_clipboard_task_24_regular"
    case .clock24Regular: return "ic_fluent_clock_24_regular"
    case .comment24Regular: return "ic_fluent_comment_24_regular"
    case .dataBarVertical24Regular: return "ic_fluent_data_bar_vertical_24_regular"
    case .delete24Regular: return "ic_fluent_delete_24_regular"
    case .desktop24Regular: return "ic_fluent_desktop_24_regular"
    case .dismiss24Regular: return "ic_fluent_dismiss_24_regular"
    case .dismissCircle24Filled: return "ic_fluent_dismiss_circle_24_filled"
    case .dismissCircle24Regular: return "ic_fluent_dismiss_circle_24_regular"
    case .document24Regular: return "ic_fluent_document_24_regular"
    case .edit24Filled: return "ic_fluent_edit_24_filled"
    case .edit24Regular: return "ic_fluent_edit_24_regular"
    case .emoji24Filled: return "ic_fluent_emoji_24_filled"
    case .errorCircle24Filled: return "ic_fluent_error_circle_24_filled"
    case .eye24Filled: return "ic_fluent_eye_24_filled"
    case .eye24Regular: return "ic_fluent_eye_24_regular"
    case .eyeOff24Regular: return "ic_fluent_eye_off_24_regular"
    case .folder24Regular: return "ic_fluent_folder_24_regular"
    case .globe24Regular: return "ic_fluent_globe_24_regular"
    case .grid24Regular: return "ic_fluent_grid_24_regular"
    case .hatGraduation24Filled: return "ic_fluent_hat_graduation_24_filled"
    case .heart24Filled: return "ic_fluent_heart_24_filled"
    case .home24Regular: return "ic_fluent_home_24_regular"
    case .homePerson24Regular: return "ic_fluent_home_person_24_regular"
    case .image24Regular: return "ic_fluent_image_24_regular"
    case .info24Filled: return "ic_fluent_info_24_filled"
    case .info24Regular: return "ic_fluent_info_24_regular"
    case .infoShield20Filled: return "ic_fluent_info_shield_20_filled"
    case .lightbulb24Filled: return "ic_fluent_lightbulb_24_filled"
    case .list24Regular: return "ic_fluent_list_24_regular"
    case .location24Filled: return "ic_fluent_location_24_filled"
    case .location24Regular: return "ic_fluent_location_24_regular"
    case .lockClosed24Filled: return "ic_fluent_lock_closed_24_filled"
    case .lockShield24Regular: return "ic_fluent_lock_shield_24_regular"
    case .mail24Filled: return "ic_fluent_mail_24_filled"
    case .mail24Regular: return "ic_fluent_mail_24_regular"
    case .mailInbox24Regular: return "ic_fluent_mail_inbox_24_regular"
    case .moreHorizontal24Regular: return "ic_fluent_more_horizontal_24_regular"
    case .people24Filled: return "ic_fluent_people_24_filled"
    case .people24Regular: return "ic_fluent_people_24_regular"
    case .peopleCommunity24Filled: return "ic_fluent_people_community_24_filled"
    case .peopleCommunity24Regular: return "ic_fluent_people_community_24_regular"
    case .person24Filled: return "ic_fluent_person_24_filled"
    case .person24Regular: return "ic_fluent_person_24_regular"
    case .personKey24Regular: return "ic_fluent_person_key_24_regular"
    case .personStarburst20Regular: return "ic_fluent_person_starburst_20_regular"
    case .phone24Filled: return "ic_fluent_phone_24_filled"
    case .phone24Regular: return "ic_fluent_phone_24_regular"
    case .phoneDismiss24Regular: return "ic_fluent_phone_dismiss_24_regular"
    case .questionCircle24Filled: return "ic_fluent_question_circle_24_filled"
    case .questionCircle24Regular: return "ic_fluent_question_circle_24_regular"
    case .road24Regular: return "ic_fluent_road_24_regular"
    case .search24Regular: return "ic_fluent_search_24_regular"
    case .shareIos24Regular: return "ic_fluent_share_ios_24_regular"
    case .shieldCheckmark24Regular: return "ic_fluent_shield_checkmark_24_regular"
    case .signOut24Regular: return "ic_fluent_sign_out_24_regular"
    case .slideTextSparkle24Regular: return "ic_fluent_slide_text_sparkle_24_regular"
    case .sparkle24Regular: return "ic_fluent_sparkle_24_regular"
    case .speaker224Filled: return "ic_fluent_speaker_2_24_filled"
    case .star24Filled: return "ic_fluent_star_24_filled"
    case .subtract24Regular: return "ic_fluent_subtract_24_regular"
    case .tablet24Regular: return "ic_fluent_tablet_24_regular"
    case .ticketDiagonal24Regular: return "ic_fluent_ticket_diagonal_24_regular"
    case .video24Filled: return "ic_fluent_video_24_filled"
    case .wallet24Regular: return "ic_fluent_wallet_24_regular"
    case .warning24Filled: return "ic_fluent_warning_24_filled"
    case .warning24Regular: return "ic_fluent_warning_24_regular"
    case .weatherMoon24Filled: return "ic_fluent_weather_moon_24_filled"
    case .weatherMoon24Regular: return "ic_fluent_weather_moon_24_regular"
    case .weatherSunny24Filled: return "ic_fluent_weather_sunny_24_filled"
    case .weatherSunny24Regular: return "ic_fluent_weather_sunny_24_regular"
    case .wifiWarning24Regular: return "ic_fluent_wifi_warning_24_regular"
    }
  }

  public var codeSnippet: String {
    switch self {
    case .accessibility24Regular: return ".accessibility24Regular"
    case .add24Filled: return ".add24Filled"
    case .add24Regular: return ".add24Regular"
    case .alert24Filled: return ".alert24Filled"
    case .alert24Regular: return ".alert24Regular"
    case .alertBadge24Filled: return ".alertBadge24Filled"
    case .appsList24Regular: return ".appsList24Regular"
    case .arrowLeft24Regular: return ".arrowLeft24Regular"
    case .arrowRepeatAll24Regular: return ".arrowRepeatAll24Regular"
    case .arrowRight24Regular: return ".arrowRight24Regular"
    case .arrowUpRight24Regular: return ".arrowUpRight24Regular"
    case .bookmark24Filled: return ".bookmark24Filled"
    case .bookmark24Regular: return ".bookmark24Regular"
    case .briefcase24Filled: return ".briefcase24Filled"
    case .briefcase24Regular: return ".briefcase24Regular"
    case .building24Filled: return ".building24Filled"
    case .building24Regular: return ".building24Regular"
    case .calendar24Regular: return ".calendar24Regular"
    case .calendarClock24Regular: return ".calendarClock24Regular"
    case .calendarEmpty24Regular: return ".calendarEmpty24Regular"
    case .camera24Filled: return ".camera24Filled"
    case .chat24Regular: return ".chat24Regular"
    case .checkmark24Filled: return ".checkmark24Filled"
    case .checkmarkCircle24Filled: return ".checkmarkCircle24Filled"
    case .checkmarkCircle24Regular: return ".checkmarkCircle24Regular"
    case .checkmarkStarburst24Filled: return ".checkmarkStarburst24Filled"
    case .chevronDown20Filled: return ".chevronDown20Filled"
    case .chevronDown24Regular: return ".chevronDown24Regular"
    case .chevronLeft24Regular: return ".chevronLeft24Regular"
    case .chevronRight24Regular: return ".chevronRight24Regular"
    case .chevronUp20Filled: return ".chevronUp20Filled"
    case .circleHalfFill24Regular: return ".circleHalfFill24Regular"
    case .clipboardTask24Regular: return ".clipboardTask24Regular"
    case .clock24Regular: return ".clock24Regular"
    case .comment24Regular: return ".comment24Regular"
    case .dataBarVertical24Regular: return ".dataBarVertical24Regular"
    case .delete24Regular: return ".delete24Regular"
    case .desktop24Regular: return ".desktop24Regular"
    case .dismiss24Regular: return ".dismiss24Regular"
    case .dismissCircle24Filled: return ".dismissCircle24Filled"
    case .dismissCircle24Regular: return ".dismissCircle24Regular"
    case .document24Regular: return ".document24Regular"
    case .edit24Filled: return ".edit24Filled"
    case .edit24Regular: return ".edit24Regular"
    case .emoji24Filled: return ".emoji24Filled"
    case .errorCircle24Filled: return ".errorCircle24Filled"
    case .eye24Filled: return ".eye24Filled"
    case .eye24Regular: return ".eye24Regular"
    case .eyeOff24Regular: return ".eyeOff24Regular"
    case .folder24Regular: return ".folder24Regular"
    case .globe24Regular: return ".globe24Regular"
    case .grid24Regular: return ".grid24Regular"
    case .hatGraduation24Filled: return ".hatGraduation24Filled"
    case .heart24Filled: return ".heart24Filled"
    case .home24Regular: return ".home24Regular"
    case .homePerson24Regular: return ".homePerson24Regular"
    case .image24Regular: return ".image24Regular"
    case .info24Filled: return ".info24Filled"
    case .info24Regular: return ".info24Regular"
    case .infoShield20Filled: return ".infoShield20Filled"
    case .lightbulb24Filled: return ".lightbulb24Filled"
    case .list24Regular: return ".list24Regular"
    case .location24Filled: return ".location24Filled"
    case .location24Regular: return ".location24Regular"
    case .lockClosed24Filled: return ".lockClosed24Filled"
    case .lockShield24Regular: return ".lockShield24Regular"
    case .mail24Filled: return ".mail24Filled"
    case .mail24Regular: return ".mail24Regular"
    case .mailInbox24Regular: return ".mailInbox24Regular"
    case .moreHorizontal24Regular: return ".moreHorizontal24Regular"
    case .people24Filled: return ".people24Filled"
    case .people24Regular: return ".people24Regular"
    case .peopleCommunity24Filled: return ".peopleCommunity24Filled"
    case .peopleCommunity24Regular: return ".peopleCommunity24Regular"
    case .person24Filled: return ".person24Filled"
    case .person24Regular: return ".person24Regular"
    case .personKey24Regular: return ".personKey24Regular"
    case .personStarburst20Regular: return ".personStarburst20Regular"
    case .phone24Filled: return ".phone24Filled"
    case .phone24Regular: return ".phone24Regular"
    case .phoneDismiss24Regular: return ".phoneDismiss24Regular"
    case .questionCircle24Filled: return ".questionCircle24Filled"
    case .questionCircle24Regular: return ".questionCircle24Regular"
    case .road24Regular: return ".road24Regular"
    case .search24Regular: return ".search24Regular"
    case .shareIos24Regular: return ".shareIos24Regular"
    case .shieldCheckmark24Regular: return ".shieldCheckmark24Regular"
    case .signOut24Regular: return ".signOut24Regular"
    case .slideTextSparkle24Regular: return ".slideTextSparkle24Regular"
    case .sparkle24Regular: return ".sparkle24Regular"
    case .speaker224Filled: return ".speaker224Filled"
    case .star24Filled: return ".star24Filled"
    case .subtract24Regular: return ".subtract24Regular"
    case .tablet24Regular: return ".tablet24Regular"
    case .ticketDiagonal24Regular: return ".ticketDiagonal24Regular"
    case .video24Filled: return ".video24Filled"
    case .wallet24Regular: return ".wallet24Regular"
    case .warning24Filled: return ".warning24Filled"
    case .warning24Regular: return ".warning24Regular"
    case .weatherMoon24Filled: return ".weatherMoon24Filled"
    case .weatherMoon24Regular: return ".weatherMoon24Regular"
    case .weatherSunny24Filled: return ".weatherSunny24Filled"
    case .weatherSunny24Regular: return ".weatherSunny24Regular"
    case .wifiWarning24Regular: return ".wifiWarning24Regular"
    }
  }
}
